Feature/131 invoice ants
hundehausen/tipxmr pull request #129
Opened 2021-03-21 11:57 UTC by AlexAnarcho

Invoice as a Modal, no tailwindcss anymore, however functionality with the actual payment/confirmation is still missing. Created a new Ticket (133) for this task.

Modal can be viewed currently at localhost.../invoice

Also created helper classes in styles/index.less for text-center and text-left

2021-03-21 13:04 UTC, hundehausen requested changes
I know the code I annotated is from me 🤪

2021-03-21 13:04 UTC, hundehausen commented on src/pages/InvoiceModal.jsx
> +  const [paymentUri, setPaymentUri] = useState(null);
remove because unnessesary

2021-03-21 13:04 UTC, hundehausen commented on src/pages/InvoiceModal.jsx
> +    return uri;
const createPaymentUri = () => {
   return amount > 0 ? `monero:${subaddress}?tx_amount=${amount}` : `monero:${subaddress}`;
}

2021-03-21 13:04 UTC, hundehausen commented on src/pages/InvoiceModal.jsx
> +      if (subaddress !== null) {
if (subaddress)

2021-03-22 09:05 UTC, AlexAnarcho commented on src/pages/InvoiceModal.jsx
> +  const [paymentUri, setPaymentUri] = useState(null);
I dont understand. these states are necessary for the payment.

2021-03-22 09:57 UTC, hundehausen approved these changes

2021-03-22 09:57 UTC, merged